### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by berg78** [SimplySynced/ha-nhl#6]
I get an error when trying to set up, this is my log?
Maybe someone can help me.

-------------------------------------------

Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: August 8, 2024 at 22:06:43 (5 occurrences)
Last logged: 09:31:52

Error setting up entry NHL for nhl
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nhl/__init__.py", line 80, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?

**Comment by dexdeadly** [comment]
I need to look at updating this soon as I can to work with the latest home assistant.
